### ISSUE TITLE
Unable to install package to the project

### ISSUE THREAD

**Issue by happyBanshee** [dncuug/X.PagedList#100]
I tried to install latest version of X.PagedList.7.2.2 and get this message >>

Could not install package 'X.PagedList 7.2.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ernado-x** [comment]
Please update your project at lease to .NET 4.5.2 version.
This package support .NET 4.5.2 and newer version: https://www.nuget.org/packages/X.PagedList/
