### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.1.1.0 after project update to Framework 4.7.1

### ISSUE THREAD

**Issue by hesta96** [dncuug/X.PagedList#101]
We have updated our project to .NET Framework 4.7.1 and reinstalled all packages to point to that version.
Now when running the project we get this error:
`Server Error in '/' Application.
While loading .NET types from "X.PagedList.Mvc" the following error(s) was reported:

    - System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

**Comment by ernado-x** [comment]
Sorry, I can't reproduce problem. Please try - https://github.com/dotnet/corefx/issues/21045
