### ISSUE TITLE
Is there a version to use for WPF app instead on MVC?

### ISSUE THREAD

**Issue by CrestApps** [dncuug/X.PagedList#106]
This is a great package that I am using in my MVC apps. I am now working on WPF app. Is there a way to use this package in WPF project?

I need the same functionality I just need more info about the collection instead of using `@Html.PagedListPager` to render the pages. I would either need a different way to render the data or get the info about my collection with in my ViewModel to determine the total pages, next page, previous page, last page.....

**Comment by ernado-x** [comment]
Unfortunately I have no experience with WPF, but you can propose your implementation via pull request.
