### ISSUE TITLE
Getting conflict in MVC version in @HTML.PagedListPager

### ISSUE THREAD

**Issue by Aravin** [dncuug/X.PagedList#107]
When I used
@Html.PagedListPager((IPagedList)ViewBag.OnePageOfProducts, page => Url.Action("Index", new { page }))

I am getting MVC version conflict.

### Error
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	CS1702	Assuming assembly reference 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' used by 'X.PagedList.Mvc' matches identity 'System.Web.Mvc, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' of 'System.Web.Mvc', you may need to supply runtime policy	CouriersHub	G:\Projects\Varun Enterprieses\CouriersHub\CouriersHub\CouriersHub\Views\Booking\Index.cshtml	113	Active	The two assemblies differ in release and/or version number. For unification to occur, you must specify directives in the application's .config file, and you must provide the correct strong name of an assembly.

### Screenshot
![image](https://user-images.githubusercontent.com/4869265/37421016-48492cf2-27de-11e8-98a7-e01bb75a88ec.png)

**Comment by ernado-x** [comment]
I think you need configure binding redirects for System.Web.Mvc

**Comment by Aravin** [comment]
It is common issue in .NET.

Just use this dependentAssembly tab within runtime section.

```
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="5.2.3.0" newVersion="5.2.4.0" />
      </dependentAssembly>
```

`oldVersion` - Conflict.
`newVersion` - Version you want to use.

So, I am redirecting 5.2.3.0 to 5.2.4.0
