### ISSUE TITLE
Argument out of range with 0 items in superset

### ISSUE THREAD

**Issue by sorcer1** [dncuug/X.PagedList#111]
Hello,

I have a List<T> with 0 items and i try to get a IPagedList<T>, when i call ToPagedList() i have an exception :

```
var list = await queryable.ToListAsync();
return list.ToPagedList();
```

> Specified argument was out of the range of valid values.\r\nParameter name: pageSize = 0. PageSize cannot be less than 1.
> 
> at X.PagedList.BasePagedList`1..ctor(Int32 pageNumber, Int32 pageSize, Int32 totalItemCount)
> at X.PagedList.PagedList`1..ctor(IQueryable`1 superset, Int32 pageNumber, Int32 pageSize)
> at X.PagedList.PagedListExtensions.ToPagedList[T](IEnumerable`1 superset)

**Comment by ernado-x** [comment]
Closed by 9cca40b5f126a83c2b46cad83a8a7bc7dd78b4fa
