### ISSUE TITLE
Empty list causes exception

### ISSUE THREAD

**Issue by zHaytam** [dncuug/X.PagedList#115]
Hello,

When using PagedList and when we don't know the length of our lists (so we can't make sure its > 0) an exception is thrown.

How can this be handled? PagedList doesn't even have an empty constructor :/

Thank you.

**Comment by ernado-x** [comment]
Can you provide example of code when you got exception?

**Comment by zHaytam** [comment]
**Example code:**
```
var articles = _someService.GetArticles(...);
var pagedArticles = new PagedList<PartnerArticle>(articles, pageNumber, 9); // Exception here
```

**Exception:**

> ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: pageNumber = 0. PageNumber cannot be below 1.
> _X.PagedList.BasePagedList..ctor(int pageNumber, int pageSize, int totalItemCount)_

**Comment by zHaytam** [comment]
I think you fixed it in this commit (https://github.com/dncuug/X.PagedList/commit/9cca40b5f126a83c2b46cad83a8a7bc7dd78b4fa) by checking `pageSize < 0` instead of `pageSize < 1` but it seems to not work in the nuget package.

**Comment by ernado-x** [comment]
Should be fixed in latest release
