### ISSUE TITLE
Can we have an overload with a `startPageSize` instead of `startSize`

### ISSUE THREAD

**Issue by VictorioBerra** [dncuug/X.PagedList#116]
Sometimes we don't have access to the page we're on, but we do have the value for "skip". Can we please have an overload that just passes the value right down to skip instead of doing the math IE: `(pageNumber - 1) * pageSize`?

One such library that this would be really helpful with is this one: https://datatables.net/manual/server-side notice it sends `start` and `length`.

I realize this can be calculated server side via `return start == 0 ? 1 : start / length;`

**Comment by chukwuemekanweke** [comment]
Hey VictorioBerra, so what value are you referring to when you say "the value right down to skip". Are you referring to the index of the record you want to use as the start record or what?

**Comment by chukwuemekanweke** [comment]
Hey @VictorioBerra, so what value are you referring to when you say "the value right down to skip". Are you referring to the index of the record you want to use as the start record or what?

**Comment by VictorioBerra** [comment]
Its been a while but yeah I think that is what I meant.
