### ISSUE TITLE
CS1702 Error when using ASP.NET MVC 5.2.6

### ISSUE THREAD

**Issue by doggy8088** [dncuug/X.PagedList#118]
I got a few warnings when using ASP.NET MVC 5.2.6.  Here is the warning message below:

> CS1702	Assuming assembly reference 'System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' used by 'X.PagedList.Mvc' matches identity 'System.Web.Mvc, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' of 'System.Web.Mvc', you may need to supply runtime policy

Screenshot below:

![image](https://user-images.githubusercontent.com/88981/43363308-8fed2c68-9334-11e8-9ddd-23643d571ae3.png)

**Comment by rhousham** [comment]
I also get this error. I know before you said about binding redirects
_I think you need configure binding redirects for System.Web.Mvc_

I've tried adding things like this to my web.config but to no avail.
<dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.6.0" />
      </dependentAssembly>
or
 <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.6.0" newVersion="5.2.6.0" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.6.0" />
      </dependentAssembly>

Any ideas?

**Comment by Aravin** [comment]
It is common issue in .NET.

Just use this dependentAssembly tab within runtime section.

```
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.6.0" />
      </dependentAssembly>
```

`oldVersion` - Conflict.
`newVersion` - Version you want to use.

So, I am redirecting any version from 0 .. 5.2.3.0 to 5.2.6.0

**Comment by rhousham** [comment]
Yeah, put that in my root web.config
```
 <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" culture="neutral" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.6.0" />
      </dependentAssembly>
</assemblyBinding>
 <runtime>

Still has the squiggle like the ticket. Closed open the ticket tried the  culture="neutral" still no dice.

So yeah, at a loss.



```

**Comment by ernado-x** [comment]
This problem should be fixed after project package version was updated in new version (will be released  in few hours).
If problem not gone, please reopen this issue.

**Comment by rhousham** [comment]
Excellent! Thanks looks great!
Cheers!
Richard

**Comment by rhousham** [comment]
Same thing has come back with MVC 5.2.7

**Comment by doggy8088** [comment]
@ernado-x The problem happen again in MVC 5.2.7.
