### ISSUE TITLE
EnableUnobtrusiveAjaxReplacing not working with two parameters

### ISSUE THREAD

**Issue by macfs36** [dncuug/X.PagedList#119]
Hello

When I use code 1 the pagination works with ajax perfectly, when I use code 2 the pagination happens without ajax, can you tell me how to fix this?

Code 1: Works with Ajax
@Html.PagedListPager(Model, page => Url.Action("IndexPartial", new { page }), 
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "divReplaceListagem" }))

Code 2 Not Works with Ajax
@Html.PagedListPager(Model, page => Url.Action("IndexPartial", new { page }),     PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(PagedListRenderOptions.OnlyShowFivePagesAtATime, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "divReplaceListagem" }))

Thank you.

**Comment by gioscaduto** [comment]
Hello.

I've gotten a problem with css class.

This code works:

  @Html.PagedListPager(Model, page => Url.Action("Listar", "CaixaEntrada", new { pagina = page }),
                       new PagedListRenderOptions()
                       { FunctionToTransformEachPageLink = (liTag, aTag) => { aTag.Attributes.Add("class", "page-link".ToString()); return aTag; },
                           LiElementClasses = new[] { "page-item" },
                           UlElementClasses = new[] { "pagination  justify-content-center" } })


But this code doesn't work:

 @Html.PagedListPager(Model, page => Url.Action("Listar", "CaixaEntrada", new { pagina = page }),
                        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
                        {   FunctionToTransformEachPageLink = (liTag, aTag) =>
                            {
                                aTag.Attributes.Add("class", "page-link".ToString());
                                return aTag;
                            },
                        LiElementClasses = new[] { "page-item" },
                        UlElementClasses = new[] { "pagination  justify-content-center" } }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "fileListTable" }))
