### ISSUE TITLE
Disable Paging for Printing

### ISSUE THREAD

**Issue by amberino** [dncuug/X.PagedList#123]
I'm using your paging solution and it works great. I was wondering if there was a way to disable the pager so that a user can print the full set of results. Do you know if this is possible?

**Comment by ernado-x** [comment]
I think you can implement this logic in your app: pass special parameter for page in (ex. printMode=true) and if this parameter is present, your controller should return all data and your view should hide pages.

**Comment by amberino** [comment]
Hello,

Thanks for your reply. I’m a VB Webforms developer who recently switched to MVC C#. Could you provide an example?

Amber Cairns |  Senior Applications Developer
P: 816.478.0120 | F: 816.478.0239
1600 NE Coronado Dr. Blue Springs, MO 64014
[cid:image001.jpg@01D41931.513D49D0]
     HFGagents.com<http://www.hfgagents.com/> | Like us on Facebook<https://www.facebook.com/HeartlandFinancialGroup/>

Information contained in this message may be privileged or confidential.  If you are not the person intended (or authorized) to receive it, do not copy or forward it to anyone.  Please reply to the sender that you received this message by mistake and then delete it.
