### ISSUE TITLE
Working with icons

### ISSUE THREAD

**Issue by mistersam91** [dncuug/X.PagedList#124]
Hi,

I would like to add font awesome icon in the pager, what property of PagedListRenderOptions should i use ??

Check the capture to see what i'm looking for : fa fa-angle-double-left icon

![capture](https://user-images.githubusercontent.com/18660099/46358498-5f716c00-c667-11e8-851b-125fde6b1a57.PNG)

**Comment by federico-66** [comment]
Hi,
try this in PagedListRenderOptions:
```
LinkToFirstPageFormat = "<i class='fas fa-angle-double-left'></i>",
LinkToPreviousPageFormat = "<i class='fas fa-angle-left'></i>",
LinkToNextPageFormat = "<i class='fas fa-angle-right'></i>",
LinkToLastPageFormat = "<i class='fas fa-angle-double-right'></i>",
```
