### ISSUE TITLE
Error when using ASP.NET MVC 5.2.7

### ISSUE THREAD

**Issue by rhousham** [dncuug/X.PagedList#130]
This issue has come back with MVC 5.2.7
https://github.com/dncuug/X.PagedList/issues/118

**Comment by wishnoblog** [comment]
i got same one.

**Comment by romelyumang** [comment]
I got this message:

Assuming assembly reference 'System.Web.Mvc, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' used by 'X.PagedList.Mvc' matches identity 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' of 'System.Web.Mvc', you may need to supply runtime policy.

**Comment by jasper-lai** [comment]
I have the sames issue

**Comment by EdwinRoestenburg** [comment]
Same issue.

**Comment by XIAOXIAOSIYU** [comment]
Same issue here.

**Comment by acscoderCrystal** [comment]
I forked a copy of this and opened it up in VS.  Opened up the Nuget package manager and then updated ALL of the packets that showed they had updates for the project before saving and rebuilding.  Fixed the issue.

**Comment by ernado-x** [comment]
Should be fixed with new version. 
Now it reference to ASP.NET MVC 5.2.7: https://github.com/dncuug/X.PagedList/blob/master/src/X.PagedList.Mvc/X.PagedList.Mvc.csproj#L22


New version is here: https://www.nuget.org/packages/X.PagedList.MVC/7.9.0
