### ISSUE TITLE
Suggest HtmlEncoder.Default as default encoding or allowing custom encoding in config 

### ISSUE THREAD

**Issue by zhengchun** [dncuug/X.PagedList#132]
In the `X.PagedList.Mvc.Core` project, a `TagBuilderToString()` method taken `TextEncoderSettings` as default encoding that will auto encoding all HTML tag including attribute value, for example, `<ul class="&#x6A;&#x75;&#x73;&#x74;&#x69;&#x66;&#x79;&#x2D;&#x63;&#x6F;&#x6E;&#x74;&#x65;&#x6E;&#x74;&#x2D;&#x63;&#x65;&#x6E;&#x74;&#x65;&#x72;&#x20;&#x70;&#x61;&#x67;&#x69;&#x6E;&#x61;&#x74;&#x69;&#x6F;&#x6E;&#x2D;&#x6C;&#x67;&#x20;&#x70;&#x61;&#x67;&#x69;&#x6E;&#x61;&#x74;&#x69;&#x6F;&#x6E;"><li class="&#x70;&#x61;&#x67;&#x65;&#x2D;&#x69;&#x74;&#x65;&#x6D;&#x20;&#x61;&#x63;&#x74;&#x69;&#x76;&#x65;"><span class="&#x70;&#x61;&#x67;&#x65;&#x2D;&#x6C;&#x69;&#x6E;&#x6B;">`
But i want HTML output like this: `<ul class=""justify-content-center pagination-lg pagination">....</ul>`. 

The other question is about page ellipses.

```c#
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }),
new X.PagedList.Mvc.Common.PagedListRenderOptionsBase() {
    DisplayEllipsesWhenNotShowingAllPageNumbers=true,
    PageClasses=new string[] {"page-link"}
})
```
In the above code, I add `page-link` class for each of page link, the ellipse link output is: `<li><a class="page-link" href="/?page=16">16</a></li><li class="disabled PagedList-ellipses"><a>…</a></li>`, in actually , ellipse link also should add `page-link` class. `<li class="disabled PagedList-ellipses"><a class="page-link">…</a></li>`

**Comment by fatagun** [comment]
I am having the same problem. seeing cryptic letters as following in the source code:

```
<div class="&#x70;&#x61;&#x67;&#x69;&#x6E;&#x61;&#x74;&#x69;&#x6F;&#x6E;&#x2D;&#x63;&#x6F;&#x6E;&#x74;&#x61;&#x69;&#x6E;&#x65;&#x72;">
```

How can I fix this?

**Comment by zhengchun** [comment]
To fix this problem, you need to change source code.  

https://github.com/dncuug/X.PagedList/blob/7a36c63f0fca918a85f1b5789b035ddd3c232980/src/X.PagedList.Mvc.Core/HtmlHelper.cs#L28

to 

```c#
private static string TagBuilderToString(TagBuilder tagBuilder, TagRenderMode renderMode = TagRenderMode.Normal)
        {
            //var encoder = HtmlEncoder.Create(new TextEncoderSettings());
            var encoder = HtmlEncoder.Default;
            var writer = new System.IO.StringWriter() as TextWriter;
            tagBuilder.WriteTo(writer, encoder);
            return writer.ToString();
        }
```
