### ISSUE TITLE
Bug in tag helper @Html.PagedListPager

### ISSUE THREAD

**Issue by TihomirMihaylov** [dncuug/X.PagedList#133]
Since I updated ASP.NET Core to ver. 2.2 the tag helper @Html.PagedListPager stopped to generate href attribute in links. If I change the name of the lambda expression from "page" to "pageNumber" for example (In the Controller class also) it starts working again.
@Html.PagedListPager((IPagedList)Model, pageNumber => Url.Action("All", new { pageNumber })) //If the name is page it goesn't work

**Comment by huuquyasb** [comment]
same issues

**Comment by rmjcsltd** [comment]
Hi @TihomirMihaylov, if my understanding is correct then I do not think this is a problem with X.PagedList. The parameter names in the lambda expression should not make a difference when it is used. My guess is that your routes are expecting a parameter called pageNumber, but when the lambda expression is used it will be something like this Url.Action("All", new { 1 }) and this is not getting mapped. You might be able to fix your problem like this; @Html.PagedListPager((IPagedList)Model, p => Url.Action("All", new { pageNumber = p }))

Hope this helps, Rhys.

**Comment by phsoftware** [comment]
I have the same problem with .net core 2.2. Works only with "pageNumber". Thanks @TihomirMihaylov 

Pierre ;)

**Comment by intrixius** [comment]
I can confirm: 
this is not working:
`@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }),
`
this is working
`@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { pageNumber = page }),
`

**Comment by KoenJanssensPD** [comment]
I can confirm:
this is not working:
`@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }), 
`this is working
`@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { pageNumber = page }),
`

**Comment by SonnyRR** [comment]
I am also experiencing the same behaviour as described in previous replies.
This works:
`@Html.PagedListPager(Model, page => Url.Action("All", new { p = page }))`
when bound as this:
`public async Task<IActionResult> All([FromQuery(Name = "p")]int? page)`

The tag helper sample. given in the README does not work :/

**Comment by alperalpdogan** [comment]
Having the same issue this thread saved me lots of time. Thanks! @TihomirMihaylov
