### ISSUE TITLE
PageClasses fails to add class onto anchor link of .pageCountAndLocation

### ISSUE THREAD

**Issue by blachawk** [dncuug/X.PagedList#142]
With X.PagedList installed in ASP.NET Classic MVC project, I have the following code added to my _Partial View:

```razor
  @Html.PagedListPager(
        Model.VolunteerActivitiesViews,
        page => Url.Action(refreshAction,
        new { page, currentSort = Model.CurrentSort, yearId = Model.YearId }
        ),
        new PagedListRenderOptions(Model.VolunteerActivitiesViews.PageCount)
        {
          LiElementClasses = new string[] { "page-item" },
          PageClasses = new string[] { "page-link" },
        }
      )
```

And this is working fine in adding `page-item` and 'page-link' where needed, **except** on 

```razor
<li class="page-item disabled PagedList-pageCountAndLocation"><a>Page 1 of 60.</a></li>
```

as  you can see the `<a>` element does not have `class='page-link'`. How can I apply it there as well?

**Comment by rmjcsltd** [comment]
I hit a similar problem with the A tags inside PagedList-skipToPrevious/PagedList-skipToNext and used CSS with a child selector to target the A tags, i.e. li.PagedList-skipToPrevious > a { ... }. I agree though that it would be more helpful if the page-link class was added to the A tag. When I get time (???) I'll take a look at the source and see whether it's possible to fix this.
