### ISSUE TITLE
After updating to 7.9.1 problem with PagedListRenderOptions

### ISSUE THREAD

**Issue by bantikyan** [dncuug/X.PagedList#150]
I have `new PagedListRenderOptions` in my asp.net mvc core razor views.

After updating to 7.9.1 getting error:
The type or namespace name could not be found. ...

**Comment by SvenAelterman** [comment]
Same issue here. I updated from 7.1.0. Was there a breaking change I didn't see?

**Comment by SvenAelterman** [comment]
@bantikyan I found the solution. Some functionality was moved to the X.PagedList.Mvc.Common namespace. Add a `@using X.PagedList.Mvc.Common;` statement to your cshtml to fix the issue.

**Comment by bantikyan** [comment]
@SvenAelterman Thanks for letting me know. But I already have that namespace included.
I updated from 7.6.0.

In my cshtml view I have: 

```
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Mvc.Common;
```
and then I have:

```
var pagedListRenderOptions = new PagedListRenderOptions
    {
        DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded,
        DisplayLinkToLastPage = PagedListDisplayMode.Never,
        LinkToFirstPageFormat = "1",
        LinkToPreviousPageFormat = "←",
        LinkToNextPageFormat = "→",
        MaximumPageNumbersToDisplay = 5,
        ContainerDivClasses = new string[] { "pagination" },
        UlElementClasses = new string[] { "page-numbers" },
        PageClasses = new string[] { "page-numbers" }
    };
```
And still getting that error

**Comment by hgirish** [comment]
I had same issue. I fixed it by adding @using X.PagedList.Mvc.Core.Common (instead of @using X.PagedList.Mvc.Common). The error went away after adding this.

**Comment by ernado-x** [comment]
In latest version namespaces was updated. Please check VS/Rider suggestions for new namespaces.

**Comment by kishor-gujar** [comment]
using X.PagedList.Web.Common;
works for me

**Comment by ObadiahWilliams** [comment]
worked for me as well using version 8.1.0
X.PagedList.Web.Common
I have another project using version 8.0.7 that requires you to use 
@using X.PagedList.Mvc.Core.Common;
