### ISSUE TITLE
EF.PagedList gets all records from the database before paging with "keySelector" override

### ISSUE THREAD

**Issue by bitje** [dncuug/X.PagedList#170]
When investigating #169 , it seemed strange that the issue was not reproducible with the keySelector override. Upon further investigation I found an issue where the whole superset is retrieved from the database before paging (`Skip`ing and `Take`ing).

1. Have an EntityFramework DbContext that has some DBSet property, say "Blogs"
2. Make sure there are at least some items in the set
3. Create a query on the Blogs, e.g. `var blogs = db.Blogs`
4. Define a keySelector: `Expression<Func<Blog, int>> keySelector = b => b.BlogId`
5. Create a EF.PagedList: `var blogs = new EF.PagedList(blogs, keySelector, 1, 5)`
6. Observe that the database query is executed before applying the skip and take and the whole table is read.

(I've used a SQL Server Profiler attached to the localdb instance to verify the behaviour)

Expected behaviour: the database query is not executed until materialising with the ToList() method.

**Comment by bitje** [comment]
The `OrderBy<TSource, TKey>` method on an `IQueryable<TSource>` only accepts `Expression<Func<TSource, TKey>>` (see https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.orderby).

Since in the `InitSubset` method a `Func<T, TKey>` is passed, the `IQueryable<T>` gets cast to `IEnumerable<T>` to perform the order by operation (hence the need to call `.AsQueryable()` afterwards).

In the optimal case, an `Expression<Func<T, TKey>>` is passed as the keySelector argument of the PagedList constructor. That can be used as argument for the OrderBy directly, without having to call the `.AsQueryable()` after ordering.

**Comment by ernado-x** [comment]
Should be fixed by this code: https://github.com/dncuug/X.PagedList/blob/master/src/X.PagedList.EF/PagedList.cs#L115
