### ISSUE TITLE
EF.PagedList: do not make exceptions for pageNumber 1

### ISSUE THREAD

**Issue by bitje** [dncuug/X.PagedList#171]
Currently the EF.PagedList treats the case where pageNumber = 1 different from all other pages. This means that the query for the first page is different from the query for all other pages.

This has a couple of (slight) disadvantages: 
1. The queryplan on the SQL server has to be recompiled when switching from the first page to another page
2. Some issues only manifest themselves when requesting another page than the first (for instance if you don't have an IOrderedQueryable and don't provide a keySelector, you can get the first page but getting another throws NotSupported exception "System.NotSupportedException: 'The method 'Skip' is only supported for sorted input in LINQ to Entities. The method 'OrderBy' must be called before the method 'Skip'.'")

Specifically for EntityFramework, treating pageNumber = 1 equal to the other cases can improve (query) performance.

**Comment by ernado-x** [comment]
Closed by #176
