### ISSUE TITLE
Null in view

### ISSUE THREAD

**Issue by gurdeepsira** [dncuug/X.PagedList#174]
Hi,
I am running the code as per the instructions but in my view when I attempt to enumerate over an object in my viewbag, I get a null error.

Please advise.

**Comment by ivangrek** [comment]
Please provide an example of how to reproduce.

**Comment by gurdeepsira** [comment]
Hi, I found the issue. There was some code missing in my controller so I looked at the example code and mirrored that, which fixed the issue :(

Great solution though!
