### ISSUE TITLE
Paging depend on the user

### ISSUE THREAD

**Issue by DanielDanielDanielD** [dncuug/X.PagedList#175]
Hi and Thanks for the library,

I have a blog that shows posts and comments based on the logged in user, how can i combine paging based on user logged in?

**Comment by ivangrek** [comment]
You could filter the data by user.

**Comment by DanielDanielDanielD** [comment]
Thanks for your help, i already solved the problem :)

[https://stackoverflow.com/questions/59472900/viewmodel-with-three-different-tables-how-to-join-the-three-tables-by-lambda-in/59473366#59473366](ViewModel with three different tables, how to join the three tables by lambda into one result?)
