### ISSUE TITLE
Nuget package dependencies for X.PagedList.EF

### ISSUE THREAD

**Issue by bitje** [dncuug/X.PagedList#179]
Can the package dependencies for the nuget package of X.PagedList.EF be lowered to be in line with the X.PagedList package?

Currently it states:
.NETFramework 4.7.2 (X.PagedList has minimum requirement of 4.5)
EntityFramework (>= 6.4.0)
X.PagedList (>= 8.0.0) (not available as package on nuget, latest version is 7.9.0)

I'd really like to use the new version of X.PagedList.EF but unfortunately can't use the package with these requirements.

**Comment by ernado-x** [comment]
Will be fixed in next release.
