### ISSUE TITLE
Consolidate common namespace/assembly name

### ISSUE THREAD

**Issue by brgrz** [dncuug/X.PagedList#180]
Migrating from Troy's PagedList...

After adding the package I noticed that `PagedListRenderOptions` were missing so I went to check which packages were added and found that the X.PagedList.Web.Common package was added.

Since my views did not find the PagedListRenderOptions I checked the Views folder web.config and corrected the references to 

				<add namespace="X.PagedList" />
				<add namespace="X.PagedList.Mvc" />
				<add namespace="X.PagedList.Web.Common" />

Now that still didn't work because the PagedListRenderOptions is in `X.PagedList.Mvc.Common` namespace (had to check the source code). After fixing that everything started to work.

My suggestion would be to consolidate either the name of the package or the namespace, IMO it would make most sense to rename the package.

**Comment by ernado-x** [comment]
Different namespaces used because now we need support .NET Core and .NET Framework. And to avoid confusions namespaces was separated.
