### ISSUE TITLE
Css files missing in NuGet package

### ISSUE THREAD

**Issue by burak-tarhanli** [dncuug/X.PagedList#182]
When i install X.PagedList.Mvc via NuGet, there are no css files coming under Content directory. I examined relevant folders in the packages directory after i installed package and there either aren't no content files in. There are only lib/, .signature.p7s and X.PagedList.Mvc.7.9.1.nupkg.
I'm using .NET 4.6.1 and X.PagedList.Mvc 7.9.1.

**Comment by ernado-x** [comment]
Will be added in next release
