### ISSUE TITLE
Error: A strongly-named assembly is required

### ISSUE THREAD

**Issue by mmu69** [dncuug/X.PagedList#183]
After upgrading X.PagedList 7.9.0 to 8.0.5 in a DotNet Framework 4.8 Mvc application I get the following error:

Regel 105:</table> Regel 106: Regel 107:@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }), Bootstrap4PagedListRenderOptions.Default)
--

**To Reproduce**
Use NuGet on a Mvc project using X.PagedList to upgrade from 7.9.0 to 8.0.5

**Comment by georgeemr** [comment]
+1

**Comment by ernado-x** [comment]
Fixed by c2cfdabd2da67a1180068839aafcd69bd77137de
