### ISSUE TITLE
Document the Entity Framework integration better

### ISSUE THREAD

**Issue by GeeWee** [dncuug/X.PagedList#184]
**Is your feature request related to a problem? Please describe.**
It looks like there's a library `X.PagedList.EF.PagedList`, which seems to maintains some Entity Frameworks specific stuff. It doesn't seem to be a dependency of the main ASP.Net core, but must be installed manually.

I think it would be really nice with some documentation that this library exists, and perhaps also what it does that the normal PagedList doesn't.

**Comment by ernado-x** [comment]
Now you can find more information [here](https://github.com/dncuug/X.PagedList/wiki/X.PagedList.EF).

**Comment by GeeWee** [comment]
Woo! Awesome!
