### ISSUE TITLE
Error when Update Version from 7.9.1 to 8.0.5 You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by lehuonggiang** [dncuug/X.PagedList#186]
**Describe the bug**
You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
![image](https://user-images.githubusercontent.com/62657121/77548126-b2388680-6ee0-11ea-850e-aa72aedbb7f7.png)

Pls help me. Thanks

**Comment by ernado-x** [comment]
Which version of ASPNET  or ASPNET Core you use?

**Comment by lehuonggiang** [comment]
ASPNET MVC. Use X.PagedList Ajax

**Comment by ernado-x** [comment]
Which exactly version you use? 4.6, 4.7, 4.8, etc?

**Comment by ScottyRobson** [comment]
I am experiencing this same issue, .NET 4.8

**Comment by lehuonggiang** [comment]
.NET 4.8

**Comment by ScottyRobson** [comment]
![Capture](https://user-images.githubusercontent.com/39091842/77640857-fb292300-6f52-11ea-98e3-1a098dd9f231.PNG)

**Comment by ernado-x** [comment]
This is known .NET problem: https://github.com/dotnet/standard/issues/542#issuecomment-339328208

**Comment by ernado-x** [comment]
Added information to wiki: https://github.com/dncuug/X.PagedList/wiki/Known-issues
