### ISSUE TITLE
Error in ASP.NET MVC project when Updating Version from 7.9.1 to 8.0.5

### ISSUE THREAD

**Issue by pmarangoni** [dncuug/X.PagedList#189]
The type or namespace name 'Mvc' does not exist in the namespace 'X.PagedList' (are you missing an assembly reference?)

**Comment by georgeemr** [comment]
I'm getting Could not load file or assembly 'X.PagedList.Web.Common, Version=8.0.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required.
