### ISSUE TITLE
Keep query parameters

### ISSUE THREAD

**Issue by snowchenlei** [dncuug/X.PagedList#192]
The resulting paginated link can be automatically appended after the current page address bar parameter.
For example:
current page address: https://github.com?a=1&b=2
generated page address: 

- https://github.com?a=1&b=2&page=1
- https://github.com?a=1&b=2&page=2
- https://github.com?a=1&b=2&page=3

That's what I do now.This is not conducive to maintenance.
```
@Html.PagedListPager(Model.Products, page => Url.Action("Home", "Product", new
{
    a=1,
    b=2,
    page= page
}))
```
[sample](http://www.webdiyer.com/mvcpager/demos/urlparams/?year=2013&author=Webdiyer&city=%E5%BB%B6%E5%AE%89)

**Comment by ronaldbarendse** [comment]
You need to provide a method to generate the URL for each page, so if it needs to keep the current query string parameters, you need to manage that yourself.

In this case, you're generating a 'canonical' URL using `Url.Action()` and manually adding some additional route parameters that are appended as query strings. You can add/merge all the current query string parameters using a simple extension method: https://stackoverflow.com/questions/5818065/how-to-pass-request-querystring-to-url-action.

**Comment by snowchenlei** [comment]
Thank you.
