### ISSUE TITLE
Still an issue 

### ISSUE THREAD

**Issue by rhousham** [dncuug/X.PagedList#193]
https://github.com/dncuug/X.PagedList/issues/173

**Comment by rhousham** [comment]
Ah maybe just hasn't been pushed yet to nuget hence I've not got the update the 8.08 version

**Comment by ronaldbarendse** [comment]
This isn't a very usefull issue: please add a descriptive title (what's the issue?) and use the bug report template (on what version are you experiencing this?).

**Comment by rhousham** [comment]
Basically there is still an a tag with the class class="PagedList-skipToNext" this should be class="page-link"

**Comment by ronaldbarendse** [comment]
There are indeed multiple classes still hard-coded and those probably need their own setting on `PagedListRenderOptionsBase`, as some are set on the links (not the list items/element) or form:
- `PagedList-skipToFirst`
- `PagedList-skipToNext`
- `PagedList-skipToPrevious`
- `PagedList-pageCountAndLocation`
- `PagedList-goToPage`
- `disabled`

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L78

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L99

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L144

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L164

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L168

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L176

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L184

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L192

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L362

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L365

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L382

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L385

https://github.com/dncuug/X.PagedList/blob/9bfd6aadcf6a5d31de1facef737096e1afc78b82/src/X.PagedList.Mvc/HtmlHelper.cs#L433
