### ISSUE TITLE
Unable to upgrade from version 7.9.0 to version 8.0.7

### ISSUE THREAD

**Issue by pmarangoni** [dncuug/X.PagedList#194]
Could not install package 'X.PagedList.Mvc 8.0.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by ronaldbarendse** [comment]
This is already reported in https://github.com/dncuug/X.PagedList/issues/190. Like the error message describes, version 8.0.7 isn't compatible with .NET Framework 4.7.2, although there's no reason why it can't be... The linked issue already has an open PR to fix this: https://github.com/dncuug/X.PagedList/pull/191.

**Comment by ronaldbarendse** [comment]
@pmarangoni PR #191 is now merged, so this issue will be fixed in the next version that gets released.

As temporary 'fix', you can also restrict NuGet versions in your `packages.config` file by adding `allowedVersions="(,8)"` (but don't forget to remove this when a new compatible version gets released):
```xml
<package id="X.PagedList" version="7.9.0" targetFramework="net472" allowedVersions="(,8)" />
<package id="X.PagedList.Mvc" version="7.9.1" targetFramework="net472" allowedVersions="(,8)" />
<package id="X.PagedList.Web.Common" version="7.9.1" targetFramework="net472" allowedVersions="(,8)" />
```

**Comment by ernado-x** [comment]
New version was published: https://github.com/dncuug/X.PagedList/releases/tag/v8.1

.NET Framework support  was dropped.
