### ISSUE TITLE
Ellipses Button

### ISSUE THREAD

**Issue by hn1** [dncuug/X.PagedList#195]
If the ellipses buttons is visible, clicking it does not do anything!

**Comment by ivangrek** [comment]
Please provide more information on how to reproduce this issue

**Comment by hn1** [comment]
Well, all the other buttons have a url that it goes to when clicked, but the ellipses buttons has no url.

**Comment by ivangrek** [comment]
It's okay. They are used as separator. 
Please see # 85 to use partial view and manually adjust all your preferences.

**Comment by hn1** [comment]
Thanks for the reply.
Normally when a user clicks the ellipses (with other pagers), it has a link that is basically the next page after the page number that is just before the ellipses.

Is there anyway of achieving this functionality?
Thanks

**Comment by ivangrek** [comment]
Pleaese see the commit
This should help

**Comment by hn1** [comment]
Sorry to bother you.
Does this mean that the Nuget package now provides this functionality
correctly?
Thanks

**Comment by ivangrek** [comment]
This functionality is not yet included in the package

**Comment by hn1** [comment]
Many thanks.
Will wait for the next update.

**Comment by ernado-x** [comment]
New version was published: https://github.com/dncuug/X.PagedList/releases/tag/v8.1

.NET Framework version was dropped.
