### ISSUE TITLE
netstandard required for 8.0.7?

### ISSUE THREAD

**Issue by pmarangoni** [dncuug/X.PagedList#198]
After upgrading my ASP.NET MVC project from framework 4.72 to 4.8, I receive this error on a page that references/uses X.PageList:

`error CS0012: The type 'IEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

**Comment by hn1** [comment]
Hi,
If you upgrade to .NET 5.0, the control just breaks in so many ways, it becomes unusable.
Any ideas?

**Comment by pmarangoni** [comment]
The project with which I am using X.PagedList is not a .NET Core project.  When I upgrade it to .NET 5 I will be rearchitecting the whole thing, and most likely won't be using X.PagedList with it.

**Comment by sashapvt** [comment]
I think it's a common problem and doesn't relly on X.PagedList. We had got the same problem after upgrading one of the projects in the solution to netstandard 2.0. The possible solution you may find [here](https://github.com/dotnet/standard/issues/391) or [here ](http://learnitonweb.com/2019/11/15/3-solved-error-cs0012-the-type-object-is-defined-in-an-assembly-that-is-not-referenced-you-must-add-a-reference-to-assembly-netstandard-version2-0-0-0-cultureneutral-publickeytokencc7/).

**Comment by ernado-x** [comment]
New version was published: https://github.com/dncuug/X.PagedList/releases/tag/v8.1

.NET Framework support  was dropped.
