### ISSUE TITLE
Are there plans for a Blazor component?

### ISSUE THREAD

**Issue by KoruNL** [dncuug/X.PagedList#202]
I've been using X.PagedList in all my MVC projects.
Recently I have started developing with Blazor WebAssembly, but I can't find a Blazor component of X.PagedList. Have I missed something? Are there plans to add a Blazor component?

**Comment by ernado-x** [comment]
Not yet, but new version was published: https://github.com/dncuug/X.PagedList/releases/tag/v8.1

.NET Framework support  was dropped.
