### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by hn1** [dncuug/X.PagedList#208]
Is there any way to use this control with an Infinite Scroll script?
Has anyone tried it or are there any examples?
Thanks

**Comment by aloksharma1** [comment]
Hi, 

i have done this with troygoodies version in previous mvc 5 project, its actually pretty simple to do...
so what you have to do this is following:

1. generate paged data in a partial view or action or view component(in case of net core version)
2. hide the paging pagination control simply using css display:none
3. use javascript and ajax call once user comes into the end of viewport or element
4. simply invoke next action link when in viewport
5. grab ajax response and populate below the current div or block (in jquery you use append)
6. repeat same

hope you understand the point..

**Comment by hn1** [comment]
Hi
Thanks for your response. Greatly appreciated.
Is there any way of configuring the pager with just a next button without
the other buttons as that is the only button required for such UI.
Many thanks

**Comment by hn1** [comment]
Hi
By the way I tried it with the X.PagedList and it does not work. I think it
might have to do with the way it wraps everything in the page with a single
container.

**Comment by aloksharma1** [comment]
if you can upload a sample repo, i can do the changes to make it work containers are no issue you just need to make your js logics for taking care of the issue, sorry dont have time to upload my own... as for the buttons yes you only need next but i just used boilerplate as its hidden i dont care about it. but you can choose to do a custom pager implementation if you just want next button to render (i simply hides it for simplicity).

**Comment by hn1** [comment]
Thanks. Do you know of any samples somewhere where I can take a look?

**Comment by aloksharma1** [comment]
maybe you can use this :https://infinite-scroll.com/
