### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by hn1** [dncuug/X.PagedList#210]
Is this thing maintained any longer. It seems to be stuck on 8.0.7 forever and a day and its functionality has become so outdated for current modern websites that it seems it has been just forgotten.
If so, would appreciate a comment so that we can find an alternative.
Thanks.

**Comment by ernado-x** [comment]
New version was published: https://github.com/dncuug/X.PagedList/releases/tag/v8.1

.NET Framework version was dropped.
