### ISSUE TITLE
Missing Docs

### ISSUE THREAD

**Issue by JGMelon22** [dncuug/X.PagedList#244]
Hi! Could you please include the examples from the [original project](https://github.com/troygoode/PagedList?tab=readme-ov-file) at the README file and update the [Wiki](https://github.com/dncuug/X.PagedList/wiki) as well? The [Use PagedList in ASP.NET Core](https://github.com/dncuug/X.PagedList/wiki/Use-in-ASP.NET-and-ASP.NET-Core) and [X.PagedList](https://github.com/dncuug/X.PagedList/wiki/X.PagedList) are empty :/

**Comment by ernado-x** [comment]
Wiki was fully updated: https://github.com/dncuug/X.PagedList/wiki
