### ISSUE TITLE
Release 10.x proposal

### ISSUE THREAD

**Issue by adschmu** [dncuug/X.PagedList#271]
There are no additional changes piped at my side at the moment.

I'm not aware of your release strategy, but to make the changes available to a larger audience I would like to see a release at some point.

Since we have breaking changes (UpdateTargetId, to some extent the namespace changes), I would propose to increment the major version for this (10.x).

Changelog proposal:

**Breaking changes:**

  * Provide specific namespaces for Extensions (6ae094e4bd45)
  * Drop fake async (sync-over-async) ToPagedListAsync() Extensions: Either use the sync ones for real collections or use the proper async implementations for EF Core in X.PagedList.EF instead. (433a5823c8a2)
  * Enable and implement nullable reference type annotations for all core packages
  * Mvc.Core: Revert behavior for UpdateTargetId: No leading hash is required (f3745d89d52b)

**Improvements:**

  * Provide missing sync overload for ToPagedList (6a79a71b13cb)
  * EF: Improve List assignment in ToPagedListAsync (7f0a3e192fea)
  * Mvc.Core: Provide defaults for some properties of AjaxOptions (0795acca336f)
  * Project: Reorganize project definitions for all core packages

**Fixes:**

  * Fix logic and improve performance in ToPagedList (35a4cc988561)

**Packages:**

  * Update various dependencies
  * EF: Require specific version of Microsoft.EntityFrameworkCore based on build target (net6.0 vs. net8.0)

**Tests:**

  * Fix and improve tests
  * Test for both .NET 6 and .NET 8

**Comment by ernado-x** [comment]
Thank you a lot @adschmu  for your support in updating project!


Currently published pre-release version of packages:

- https://www.nuget.org/packages/X.PagedList/10.0.0-pre
- https://www.nuget.org/packages/X.PagedList.EF/10.0.0-pre
- https://www.nuget.org/packages/X.PagedList.Mvc.Core/10.0.0-pre


I also plan update some readme files to provide actual information about packages.

**Comment by adschmu** [comment]
There are still some issues with the project files. I'll send a quick fix in a few minutes.

**Comment by adschmu** [comment]
I've updated the changelog above since you merged the PR dropping the async-over-sync extensions.

IMHO the only change not included in the changelog above since 9.1.2 should be your recent changes to Example.Website ("Removed Ajax support and obsolated Bootstrap Ajax examples")

**Comment by ernado-x** [comment]
I want to rewrite examples because the current example project used an outdated Bootstrap version. But I need to find time for it :)

**Comment by adschmu** [comment]
How about releasing 10.0.3-pre? 10.0.1-pre release is based on a side arm of the merge, which has changes to Subset that conflict with the version actually taken later ...

**Comment by adschmu** [comment]
Consider added the following to Breaking Changes in the 10.0.3 release notes:

  `PagedList` will not accept "null" for subset (fe53b3e63f71)

**Comment by aloksharma1** [comment]
is async methods going to be rewritten, i didnt noticed before that it was just decoration before update and heavily used them in my project. now i cannot update without doing a massive rewrite everywhere.

**Comment by adschmu** [comment]
> is async methods going to be rewritten, i didnt noticed before that it was just decoration before update and heavily used them in my project. now i cannot update without doing a massive rewrite everywhere.

The async-over-sync methods removed are complete nonsense: They made everything slower and had no advantage at all.

If you want async behavior and use EF Core queries, use the PagedList.EF package that provides actual async extensions that do something useful. If you just enumerate in CPU and do not use EF Core "queries", just use the sync variants of the extensions. It will improve your code and should be straightforward to replace.

Of course, if you want to keep the pointless methods, you can simply copy the four wrappers from PagedListAsyncExtensions removed here: https://github.com/dncuug/X.PagedList/commit/433a5823c8a2ef22cca7805e270bb4f72dbb2ec2

**Comment by aloksharma1** [comment]
> PagedList.EF

thanks for the input i will explore this package instead, i was under impression that they were truly async methods.
