### ISSUE TITLE
Get Paging Url from Current Url instead?

### ISSUE THREAD

**Issue by Humbledonk** [dncuug/X.PagedList#54]
Hi,

I wonder how I can create the action link from current url and get the paging to work for it instead of building it from only a controller and action.

If this is the current url e.g: http://mydomain.com/urlparth1/urlpath2/

How can I just get the Html.PagedListPager to create paging urls like this 
http://mydomain.com/urlparth1/urlpath2/?page=1

Is this possible?

**Comment by ernado-x** [comment]
If you use `@Html.PagedListPager((IPagedList)ViewData.Model.EnumerableAds, page => Url.Action("MyPage", "Home", new { page }))`

you can replace 
```
.Action("MyPage", "Home", new { page }))
```

with your own logic for link rendering
