### ISSUE TITLE
Count must have a non-negative value. Parameter name: count

### ISSUE THREAD

**Issue by ches151** [dncuug/X.PagedList#55]
Got this error when tested my application for extreme values.
Solution: inside `PagedList` constructor, this operation `(pageNumber - 1) * pageSize` should be enclosed into `checked` statement.
Another solution would be checking the same and throwing `ArgumentOutOfRangeException("pageSize, pageNumber", "(pageSize - 1)*pageNumber cannot exceed int.MaxValue.")`

**Comment by ernado-x** [comment]
Already implemented:https://github.com/dncuug/X.PagedList/blob/master/src/X.PagedList/PagedList.cs#L42
