### ISSUE TITLE
Serialize/deserialize IPagedList<T> using JSON.NET

### ISSUE THREAD

**Issue by ronaldme** [dncuug/X.PagedList#57]
I am strugling with the serialization of IPagedList<T> using JSON.NET. 

Also asked a question on StackOverflow(1) as it is maybe not an issue with this library per se, but that I have to implement a custom serializer/deserializer to make it work.

I have the following use case, I want to serialize/deserialize my IPagedList of T using JSON.net (Newtonsoft.Json). This seems not to be working. It does not serialize everything, only the items (or with my own ContractResolver, the object with empty properties).

A test case:

var list = new List<int>(Enumerable.Range(1, 1000));
var paged = list.AsQueryable().ToPagedList(3, 10);

var json = JsonConvert.SerializeObject(paged); (output: [21,22,23,24,25,26,27,28,29,30])
var obj = JsonConvert.DeserializeObject<PagedList<int>>(json);

Questions:
1. Why do only the items get serialized? (cannot serialize back to the PagedList because of that, I guess)
2. Is there a 'known' solution to serialize the pagedlist?

Found (2) which correctly makes me serialize the PagedList but that cannot convert back to the IPagedList, are there implementations for serialization for this library?
1. http://stackoverflow.com/questions/40101674/serialize-deserialize-ipagedlistt-using-json-net?noredirect=1#comment67475706_40101674
2. https://stackoverflow.com/questions/12129774/serialize-custom-properties-on-a-class-that-implements-ienumerable

**Comment by emouawad** [comment]
+1 I think this is important.
Would be essential having this done.
Thank you.

**Comment by ernado-x** [comment]
This is not a bug. JSON support only simple arrays and cannot serialize  complex object which inherite from array type. You should resolve it manual. For ex. serialize separately PagedListMetaData object and elements.
