### ISSUE TITLE
Support generating "submit input" other than "a href"

### ISSUE THREAD

**Issue by mvpkenlin** [dncuug/X.PagedList#58]
Is it possible to add support to generating the pagination as
`<input` type="submit" `value="{pageNumber}"/>`  
from only generating 
`<a` href="generatedUrl" `/>?`

I have too many parameters have to add to the Url.Action but all the values are already under the <form> tab.

**Comment by dnxit** [comment]
Hi when this feature is expected ???
I also have a huge form with searching parameters I would also prefer a POST Action with search, sorting and paging support.

**Comment by flatproject** [comment]
This feature would be amazing as I also have a huge list of filtering parameters which i would prefer to POST when searching or paging.

**Comment by powerservephillip** [comment]
Was there ever any resolution to this?
