### ISSUE TITLE
CS0012	The type 'IEnumerable' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by mvpkenlin** [dncuug/X.PagedList#59]
I tried to replace X.PagedList from PagedList. But then there are many errors in the cshtml in my project although the project could be compiled and execute without any error. The error is as the following,

Error   CS0012  The type 'IEnumerable' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

How do we resolve it? I already target the project to .NET 4.6.1 and the version of X.PagedList is 5.3.0.5300

And my web.config already has added the following,

`<system.web>`
`<compilation debug="true" targetFramework="4.6.1" >`
`<assemblies>`
`<add assembly="System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />`
`</assemblies>`
`</compilation>`

**Comment by sashapvt** [comment]
Hi! X.PagedList is OK.

You can try to fix your problem in two ways:
1. Install in your project Microsoft.NETCore.Portable.Compatibility package:
https://www.nuget.org/packages/Microsoft.NETCore.Portable.Compatibility
"Enables compatiblity with portable libraries targeting previous .NET releases like .NET Framework 4.0 and Silverlight.
This package supports retargeting references to classic reference assemblies (mscorlib.dll, system.dll, etc) to new contract assemblies (System.Runtime.dll, System.IO, etc)..."
2. Change X.PagedList target  profile from PCL to .NetStandard1.0. See my test fork for example:
https://github.com/sashapvt/X.PagedList/tree/net-core
