### ISSUE TITLE
Async implementation

### ISSUE THREAD

**Issue by denisz1** [dncuug/X.PagedList#61]
The async implementation is using `Task.Factory.StartNew()` but that is not good in ASP.NET environment, it is better to be using the approach done by [Entity Framework here](http://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.cs#L2130) because that is not creating a new thread.

**Comment by VictorioBerra** [comment]
What about EF Core? Can we get this to tap into `ToListAsync`? https://msdn.microsoft.com/en-us/library/dn220262(v=vs.113).aspx
