### ISSUE TITLE
Version 5.3.0.5300 of X.PagedList.MVC removes the reference of X.PagedList.MVC

### ISSUE THREAD

**Issue by dubesinhower** [dncuug/X.PagedList#68]
I'm using the newest version of X.PagedList.MVC, but I do not see a reference to the package in my project. I downgraded the package to 5.1.0.5000, and the package appears.

**Comment by lgoudriaan** [comment]
I got the same problem

**Comment by mycroes** [comment]
It seems the package only contains net46 lib folder while I'm targeting 4.5 / 4.5.2

**Comment by lgoudriaan** [comment]
BTW, this is a duplicate of #52
