### ISSUE TITLE
Don't display on no data

### ISSUE THREAD

**Issue by phatcher** [dncuug/X.PagedList#72]
Is there an option to not render the pagination control if there's no data?

At the moment what I get is "Page 1 of 0" which isn't great

**Comment by sashapvt** [comment]
Try to use Default Paging Control

See demo from X.PagedList.Mvc.Example
```
     <h3>Default Paging Control</h3>
    <paged-list-pager list="@(IPagedList)ViewBag.Names" page-url="@(page => Url.Action("Index", new { page }))" />
```
Default options for control:
```
public PagedListRenderOptions()
    {
      DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded;
      DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded;
      DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded;
      DisplayLinkToNextPage = PagedListDisplayMode.IfNeeded;
// ...
```

With data:
![image](https://cloud.githubusercontent.com/assets/22121741/23677081/71ea3fbe-0387-11e7-9806-7a8bb99b57d0.png)

Without:
![image](https://cloud.githubusercontent.com/assets/22121741/23677143/99642d02-0387-11e7-9c0e-855c5fba3573.png)
