### ISSUE TITLE
X.PagedList.Mvc.Core Add support for .NET Framework 4.x

### ISSUE THREAD

**Issue by LugTread** [dncuug/X.PagedList#77]
The current X.PagedList.Mvc.Core library targets netstandard 1.6 which isn't supported in any current .NET Framework with the 1.0 tooling. This is a blocker for using this package with any ASP.NET Core applications targeting .NET Framework 4.x until the 2.0 tooling is realeased.  It would be great if the target could be rolled back to the lowest possible netstandard to provide the widest range of compatibility.

**Comment by ernado-x** [comment]
Closed by f12051a65cde18fa4cbd20bcefa1da4936c868a7
