### ISSUE TITLE
v7 assemblies are not signed

### ISSUE THREAD

**Issue by mmu69** [dncuug/X.PagedList#79]
After updating X.Pagedlist from v5.3 to v7 with NuGet, the X.Pagedlist assemblies are not signed and my MVC app will not start.
Is there a reason for not signing the assemblies?

**Comment by ernado-x** [comment]
@mmu69 , please check 7.0.1 version

**Comment by mmu69** [comment]
Signed, thank you for the quick reaction.
Could you include an updated X.Pagedlist.MVC that is referencing the new X.Pagedlist

Error	CS0012	The type 'IPagedList' is defined in an assembly that is not referenced. You must add a reference to assembly 'X.PagedList, Version=7.0.0.5500, Culture=neutral, PublicKeyToken=null'.

**Comment by ernado-x** [comment]
Sure, I will update X.Pagedlist.MVC ASAP!

**Comment by ernado-x** [comment]
@mmu69 please check https://www.nuget.org/packages/X.PagedList.Mvc/7.0.1

**Comment by ernado-x** [comment]
@mmu69 can we close this issue?
