### ISSUE TITLE
nuget is in debug mode

### ISSUE THREAD

**Issue by 1amirjalai** [dncuug/X.PagedList#80]
after installing xpagedlist and memory dumping in production x.pagedlist is in debug mode

**Comment by 1amirjalai** [comment]
this issue still exist.
the package isn't in release mode?
why does it get closed?

**Comment by ernado-x** [comment]
Please check  again. I uploaded nuget package from Release directory: 
![capture](https://user-images.githubusercontent.com/3822922/27014169-f1a1efee-4efb-11e7-8a46-3c305c1d2538.PNG)
