### ISSUE TITLE
Can't deserialize any object of IPagedList

### ISSUE THREAD

**Issue by nicholasyin** [dncuug/X.PagedList#82]
Isn't it quite common to have the paging function in a distributed environment? Well, i can't deserialize either IPagedList or any concrete type deriving from IPagedList using JSON.NET. The error message is: Cannot create and populate list type X.PagedList.StaticPagedList`1

**Comment by ernado-x** [comment]
This is by design for IEnumerable object serialization

**Comment by nicholasyin** [comment]
psst...
