### ISSUE TITLE
Custom pagination help

### ISSUE THREAD

**Issue by Voodem** [dncuug/X.PagedList#85]
Hi ,
Is it possible to change the order of li elements in the pagedlist?
Basically..I need a pagination of the attached format...is it possible to achieve it through pagedlist?
Please guide.
![custompagination](https://user-images.githubusercontent.com/31613980/30016938-8ac1272c-919a-11e7-9af8-e3eb83bb4e55.jpg)

**Comment by Almeonamy** [comment]
You can create your own pager based on data from IPagedList, that contains current page and number of pages.

**Comment by rmjcsltd** [comment]
Hi Voodem - your requirement is not clear, for example, if I was on page 10 what would the pager look like? Regards, Rhys.
