### ISSUE TITLE
Skip and Take performance issue

### ISSUE THREAD

**Issue by georgeemr** [dncuug/X.PagedList#89]
Hi, SQL have a positive performance impact when using Skip and Take a temporary variable.

Please refer to this: https://www.red-gate.com/simple-talk/dotnet/net-tools/entity-framework-performance-and-what-you-can-do-about-it/
Section: Bloating the plan cache

**The change is from this:**
```
 var schools = db.Schools
		     .OrderBy(s => s.PostalZipCode)
		     .Skip(model.Page * model.ResultsPerPage)
		     .Take(model.ResultsPerPage)
		     .ToList();
```

**To this:**
```
int ResultsPerPage = 10; // 
int resultsToSkip = model.Page * model.ResultsPerPage;
		 var schools = db.Schools
		     .OrderBy(s => s.PostalZipCode)
		     .Skip(() => resultsToSkip) //must pre-calculate this value
		     .Take(() => ResultsPerPage)
		     .ToList();
```

Here the change would be something like this:

```
public PagedList(IQueryable<T> superset, int pageNumber, int pageSize)
            : base(pageNumber, pageSize, superset.Count())
        {
            if (TotalItemCount > 0)
            {
              var pageNumber = (pageNumber - 1) * pageSize;
                Subset.AddRange(pageNumber == 1
                    ? superset.Take(() => pageSize).ToList()
                    : superset.Skip(() => pageNumber).Take(() => pageSize).ToList()
                );
            }
        }

```
This can make a query goes from 10 seconds to 0 seconds.

**Comment by georgeemr** [comment]
I would appreciate if you can change this and update the NUGET.

**Comment by ProNotion** [comment]
Have you submitted a pull request which might speed up the inclusion of this?

**Comment by Almeonamy** [comment]
I tried to submit pull request for this issue:
#94

**Comment by NicoJuicy** [comment]
I came here to request the same thing. This issue can be closed right? Considering https://github.com/dncuug/X.PagedList/pull/94

**Comment by Almeonamy** [comment]
Not yet. Pull request was be merged, but in another commit this was broken for .Net Standard supporting.

**Comment by rossiter10** [comment]
What happened to this? It looks like it was added, then (accidentally?) reverted in a later commit.

**Comment by ernado-x** [comment]
Optimized version published as separate package: https://www.nuget.org/packages/X.PagedList.EF/7.9.0

Source code: https://github.com/dncuug/X.PagedList/tree/master/src/X.PagedList.EF
