### ISSUE TITLE
@HTML.PagedListPager Does not work

### ISSUE THREAD

**Issue by konstantinosDMS** [dncuug/X.PagedList#96]
Hi I tried everything in doc but the @Html.PagedListPager() function does not recognised as valid Html function.Any suggestion?

**Comment by Almeonamy** [comment]
May be you forgot add `@using X.PagedList.Mvc` to the begin of the view file?

**Comment by Alexzxcvbnm** [comment]
Also having the same problem. Solution by @Almeonamy does not work, it just says that the using directive is necessary. It only seems to be a problem in ASP.NET core for me.

**Comment by Almeonamy** [comment]
May be you haven't reference to X.PagedList in your project?

**Comment by Alexzxcvbnm** [comment]
I tried installing all packaged manually just in case. I think it's just now working on asp.net core right now. I'd be happy if you could confirm this for me.

**Comment by ernado-x** [comment]
@Alexzxcvbnm can you please send link to project repo where it not work correct?

**Comment by Alexzxcvbnm** [comment]
@ernado-x [Here](https://github.com/Alexzxcvbnm/Test)'s an example of what I was talking about. The paged list is on /Test/Views/Home/Index.cshtml.

**Comment by cicciopage** [comment]
I have the same problem on a .net core project. I installed the package by nuget

**Comment by konstantinosDMS** [comment]
It runs localy, I fixed all the issues except for ajax case. I can;t fix it at all. Give a try and guide me because I am new on .net. I write plently PHP and Java, what do you mean with the following: Ajax library is under core installed. Do I have to do anythinh to run Ajax implementation?

**Comment by ernado-x** [comment]
Should be fixed  in 7.2.0 version - https://www.nuget.org/packages/X.PagedList.Mvc.Core/7.2.0
Please reopen this ticket it you will have this problem.

**Comment by jingliancui** [comment]
Hey, I know why ,
this because in your sample code :
`@using X.PagedList.Mvc; //import this so we get our HTML Helper`
above is wrong 

just use this:
`@using X.PagedList.Mvc.Core;`

![image](https://user-images.githubusercontent.com/16309962/34406014-abd06e9e-ebf1-11e7-9acc-7184a2c19eed.png)
